### ISSUE TITLE
Remove or increase thread limit

### ISSUE THREAD

**Issue by tameware** [online-bridge-hackathon/DDS#73]
Find out why it's there in the first place.

**Comment by suokko** [comment]
Do you mean libdds thread limit?

It is limiting number of thread private persistent cache for double dummy solver. The thread private data is large so it shouldn't be more than physical cores available. I can be configured with server.yaml. Default is to let libdds detect cores available.

**Comment by tameware** [comment]
Yes, the libdds thread limit.

I noticed in testing on my Mac that the analysis finishes substantially more quickly if I let the library set the number of threads. I do not know why our wrapper code sets a maximum of 2 by default. I'd like to know before changing it.

**Comment by suokko** [comment]
As of yesterday, the default is to let library use the automatic detection. Configuration can lower the limit if there is a need. (Same for memory use)

**Comment by tameware** [comment]
Great - thanks! Closing this issue…
