### ISSUE TITLE
List DDS on Bo Haglund's site

### ISSUE THREAD

**Issue by tameware** [online-bridge-hackathon/DDS#85]
http://privat.bahnhof.se/wb758135/bridge/users.html

**Comment by kiat-huang** [comment]
Email sent.

---------- Forwarded message ---------
From: Kiat Huang <kiat.huang@gmail.com>
Date: Mon, 21 Sep 2020 at 22:54
Subject: Bridge Hackathon is a DDS user
To: Bo Haglund <bo.haglund@bahnhof.se>
Cc: Adam Wildavsky <adam@tameware.com>


Hi Bo,
Just wanted to let you know that we are happy users of your DDS code, if you wish to add us to your users page - http://privat.bahnhof.se/wb758135/bridge/users.html
We've put a wrapper around it and made it available as a web service. 

https://github.com/online-bridge-hackathon/DDS

-- 

Kind regards,Kiat

BBO ID: kiatlinkedin.com/in/kiathuang
bit.ly/bridge-hackathon+44-7526-810553

**Comment by kiat-huang** [comment]
Done
